services:
  rathacks:
    image: nathan5471/rathacks:latest
    container_name: rathacks
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/rathacks
      - JWT_SECRET=
      - FRONTEND_URL=
      - LOOPS_API_KEY=
      - LOOPS_EMAIL_VERIFICATION_TEMPLATE_ID=
      - LOOPS_RESET_PASSWORD_TEMPLATE_ID=
      - LOOPS_WORKSHOP_STARTING_TEMPLATE_ID=
      - LOOPS_ORGANIZER_INVITE_TEMPLATE_ID=
      - LOOPS_JUDGE_INVITE_TEMPLATE_ID=
    restart: unless-stopped
    voluemts:
      - uploads:/backend/uploads
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rathacks
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  uploads:
  pgdata:
